### ISSUE TITLE
Idea: let hint text for date fields contain dynamic dates

### ISSUE THREAD

**Issue by david-mears-dfe** [DFE-Digital/govuk-formbuilder#327]
On Teaching Vacancies we have been periodically updating the hint text for places such as this _manually_, depending on whenever somebody notices that it looks weird to show dates that are not in the future:

![image](https://user-images.githubusercontent.com/60350599/142599377-9f50f539-f747-44a0-b87a-f6956451e83b.png)

We're thinking of moving to doing it dynamically as it will save overhead in the long run.

Conceivably other services might have a similar need, so once we've done this, let's talk about whether it would be a useful addition to the govuk formbuilder.

**Comment by peteryates** [comment]
This is already possible as you can set label/hint/legend/caption content [using procs](https://govuk-form-builder.netlify.app/introduction/labels-captions-hints-and-legends/#setting-label-content-with-a-proc).

```diff
-    <%= form.govuk_date_field(:delivery_date) %>
+    <%= form.govuk_date_field(
+      :delivery_date,
+      hint: -> do
+        "For example 01 01 #{Time.zone.now.year}"
+      end
+    ) %>
```

![Screenshot from 2021-11-19 09-43-50](https://user-images.githubusercontent.com/128088/142601430-c7bfa3f7-979e-48f7-bd1b-a222e329662f.png)
