### ISSUE TITLE
Conditional revealed question values

### ISSUE THREAD

**Issue by baarkerlounger** [DFE-Digital/govuk-formbuilder#362]
Form builder supports conditionally questions, nested under radio items and show or hides them based on the selected value. It doesn't seem like it clears the value of the conditionally hidden question on hide though. Should it?

E.g.:

1) ![image](https://user-images.githubusercontent.com/5101747/168877379-a7ec4b60-e773-416f-9de6-e4666bb6501a.png)
2) ![image](https://user-images.githubusercontent.com/5101747/168877430-0b00ca20-185c-47e6-8f25-a5eb36b843a0.png)
3) ![image](https://user-images.githubusercontent.com/5101747/168877379-a7ec4b60-e773-416f-9de6-e4666bb6501a.png)

**Comment by peteryates** [comment]
This is an interesting question, thank you for raising it. I don't believe it could be achieved in the form builder itself as it has no idea about which fields are conditional and doesn't come with any accompanying JavaScript. So long as the inner text field isn't `disabled` the value will be submitted.

The conditional reveal in `govuk-frontend` just hides the conditional `<div>` by toggling `govuk-radios__conditional--hidden`, [here](https://github.com/alphagov/govuk-frontend/blob/main/src/govuk/components/radios/radios.js#L86).

I think the safest approach is to check the (probably transient) submitted value for the radios in the controller and then select/omit the revealed text field attributes based on that.

If you have a lot of pages like this perhaps via naming convention it can be streamlined.

I'll mention this issue on DfE's Slack, I'm sure people have encountered and dealt with it before.

**Comment by tvararu** [comment]
> I think the safest approach is to check the (probably transient) submitted value for the radios in the controller and then select/omit the revealed text field attributes based on that.

This is what we’ve done in Find a lost TRN: https://github.com/DFE-Digital/find-a-lost-trn/blob/main/app/forms/name_form.rb#L32

The form looks like this:

![4AFB8D4B-4BC7-42BA-BBB4-A033822BF42D](https://user-images.githubusercontent.com/1650875/168915959-3f3c7fbc-5c4b-4b42-9a31-544f45905554.png)

You can write anything in the previous fields; if you deselect the checkbox and submit, the previous first name and previous last names are cleared, regardless of what’s in the actual fields.

You can play around with it here (try to progress until the Check answers page, and then try different combinations of names and previous names) https://dev-find-a-lost-trn.education.gov.uk/name

**Comment by baarkerlounger** [comment]
We're currently working around this with custom JS (https://github.com/communitiesuk/submit-social-housing-lettings-and-sales-data/blob/main/app/frontend/controllers/conditional_question_controller.js) to clear the field (backend works similarly to your example).

**Comment by peteryates** [comment]
Going to close this. I think it's outside of the form builder's remit. Happy to revisit if there's anything we can do to help.
