### ISSUE TITLE
Support hint for fieldset

### ISSUE THREAD

**Issue by JonF1** [DFE-Digital/govuk-formbuilder#369]
We had a recent accessibility issue on Apply. The check box shown below wasn't grouped with the date field, an issue for screen readers.

<img width="521" alt="Screenshot 2022-06-09 at 12 16 08" src="https://user-images.githubusercontent.com/58793682/172835237-73f1e1cc-a4aa-44ae-b441-6f4712da11fa.png">

To solve I used `govuk_fieldset` but it doesn't support a hint and I couldn't use any of the other fieldset options which support hints (checkbox etc) as the block contained a date field. This meant that I had to attach the hint to the date field, which also renders a fieldset itself. So we have the hint inside a nested fieldset. 

<img width="894" alt="Screenshot 2022-06-09 at 12 27 17" src="https://user-images.githubusercontent.com/58793682/172836293-2c1c1a70-b656-4915-b44c-30837f9e0143.png">

Ideally, we'd want the hint with the outer fieldset as it describes both the date field and the check box. Is there a simple solution for this that I've missed? Or is it possible for the formbuilder to support a hint with govuk_fieldset

**Comment by peteryates** [comment]
Alternatively you can set the fieldset's `aria-labelledby` and add a hint manually:

```
= govuk_fieldset(aria: { labelledby: some_id }) do
  = tag.p(some_hint_text, id: some_id, class: "govuk-hint")

  = govuk_date_field(:work_history_start_date, ...)

  = govuk_check_box(...)

```

**Comment by JonF1** [comment]
Thanks @peteryates, as you suggested, I can manually add the hint  - avoiding the nested fieldsets and preserving the shared label for the screenreader, cheers
