### ISSUE TITLE
Hrefs on `.govuk-error-summary__list` item links do not match IDs on `.govuk-error-message` elements

### ISSUE THREAD

**Issue by patrick-laa** [DFE-Digital/govuk-formbuilder#396]
## Using:
Ruby 3.1.2
Rails 7.0.4
FormBuilder 3.1.2

With a pre-generated scaffold for an 'Article' model.

With an model object that looks like this:

```ruby
class Article
  include ActiveModel::Model
  include ActiveModel::Attributes

  attribute :title, :string
  validates :title, presence: true
end
```

And a form partial that looks like this:

```erb
<%= form_with(model: article) do |form| %>
  <%= form.govuk_error_summary "Errors" %>

  <%= form.govuk_text_field :title, width: 20, label: { text: "Title" } %>

  <div>
    <%= form.submit %>
  </div>
<% end %>
```

When the form is submitted with the `title` field empty, the resulting error message summary snippet is as follows:

```html
<a data-turbo="false" href="#article-title-field-error">can't be blank</a>
```

And the text field snippet is as follows:

```html
<p class="govuk-error-message" id="article-title-error"><span class="govuk-visually-hidden">Error: </span>can't be blank</p>
```

I believe the expected behaviour is that the ID on the latter snippet should be `article-title-field-error`, not `article-title-error`. Otherwise the anchor href doesn't have anywhere to point to.

**Comment by patrick-laa** [comment]
Ignore me - misunderstood how this works.

**Comment by peteryates** [comment]
Was just mid way through replying 😄 Thanks Patrick!
