### ISSUE TITLE
Support inverse button style

### ISSUE THREAD

**Issue by paulrobertlloyd** [DFE-Digital/govuk-formbuilder#427]
See https://github.com/alphagov/govuk-frontend/pull/3556. Not sure what release of `govuk-frontend` this is scheduled for.

`inverse: true`?

**Comment by peteryates** [comment]
I made the changes [in a straightforward manner](https://github.com/DFE-Digital/govuk-formbuilder/commit/1d4e571aae28e3a2f5d7ec7b1b1d9f5e8056a8cc) but ran into some problems with Dart Sass compiling govuk-frontend:

```
Captain! We’ve been hit!

RuntimeError: Failed to compile Sass

Current item: /stylesheets/application.scss (:default representation)

  0. DEPRECATION WARNING: Using / for division outside of calc() is deprecated and will be removed in Dart Sass 2.0.0.
  1.
  2. Recommendation: math.div(100%, 4) or calc(100% / 4)
  3.
  4. More info and automated migrator: https://sass-lang.com/d/slash-div
  5.
  6.    ╷
  7. 22 │   one-quarter: (100% / 4),
  8.    │                 ^^^^^^^^
  9.    ╵
  ... 115 lines omitted (see crash.log for details)

A detailed crash log has been written to ./crash.log.
Listening for site changes…
```

[There's quite a bit of that going on upstream](https://github.com/alphagov/govuk-frontend/blob/839adc06ad36aeb1a982d8fd778b39c3c1ee2bae/packages/govuk-frontend/src/govuk/settings/_measurements.scss#L22).

**Comment by peteryates** [comment]
Turns out the above problem was caused by `$button-shadow-size`, so hardcoding that to the default value of `2px` lets us work around it. The custom style can be dropped after the next version of the design system is released.
